basePath: /api/v1
definitions:
  errors.CustomError:
    properties:
      code:
        type: integer
      internalCode:
        type: string
      message:
        type: string
    type: object
  model.Product:
    properties:
      additionalImages:
        items:
          type: string
        type: array
      brand:
        type: string
      name:
        type: string
      price:
        type: string
      principalImage:
        type: string
      size:
        type: string
      sku:
        type: string
    type: object
  product.FindAllProductsResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/model.Product'
        type: array
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /products/findAll:
    get:
      consumes:
      - application/json
      description: obtiene todos los productos
      operationId: findAllProductsGet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.FindAllProductsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      summary: Find all products
      tags:
      - Products
swagger: "2.0"
