-- MySQL Script generated by MySQL Workbench
-- Sat May 29 23:15:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEST` ;

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEST` DEFAULT CHARACTER SET utf8 ;
USE `TEST` ;

-- -----------------------------------------------------
-- Table `TEST`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`products` ;

CREATE TABLE IF NOT EXISTS `TEST`.`products` (
  `sku` VARCHAR(45) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `brand` VARCHAR(50) NOT NULL,
  `size` VARCHAR(10) NULL DEFAULT NULL,
  `price` INTEGER NOT NULL,
  `principalImage` TEXT NOT NULL,
  PRIMARY KEY (`sku`),
  UNIQUE INDEX `SKU_UNIQUE` (`sku` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `TEST`.`products_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`products_images` ;

CREATE TABLE IF NOT EXISTS `TEST`.`products_images` (
  `code` INTEGER NOT NULL AUTO_INCREMENT,
  `products_sku` VARCHAR(45) NOT NULL,
  `url` TEXT NULL,
  PRIMARY KEY (`code`, `products_sku`),
  UNIQUE INDEX `fk_products_images_products_idx` (`products_sku` ASC),
  CONSTRAINT `fk_products_images_products`
    FOREIGN KEY (`products_sku`)
    REFERENCES `TEST`.`products` (`sku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8;